### ISSUE TITLE
Transparent Header

### ISSUE THREAD

**Issue by slothking87** [rbogdanov/lovelace-animated-background#1]
I might have missed the code for this - But is there a way to disable the transparent header? My icons keep getting lost in the animation.

**Comment by rbogdanov** [comment]
Fixed. Add option for this. 
Please forgive me, I am just now starting to work with github. Maybe I sometimes poke the wrong buttons ;-)

**Comment by slothking87** [comment]
Thanks heaps - The next stage would be to be able to set a % transparency for the header rather than all on or all off.
