### ISSUE TITLE
Lovelace is empty.

### ISSUE THREAD

**Issue by Alexamig** [rbogdanov/lovelace-animated-background#4]
After updating HA to core-2024.5.0 it stopped working. The Lovelace background became empty.

**Comment by rbogdanov** [comment]
Yes. I see. working ;-)

**Comment by rbogdanov** [comment]
> After updating HA to core-2024.5.0 it stopped working. The Lovelace background became empty.

Yes. I see. working ;-)

**Comment by rbogdanov** [comment]
Fixed

**Comment by Alexamig** [comment]
And with the transition to HA kernel-2024.5.1, now everything works fine. Everything is fine :-) Thanks!
